# Generated by Django 5.1.1 on 2024-09-03 23:15

import ckeditor_uploader.fields
import conhecimento.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'titulo',
                    models.CharField(max_length=255, verbose_name='Título'),
                ),
                (
                    'categorias',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='Categoriais'
                    ),
                ),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    'validade',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        validators=[conhecimento.models.validate_future_date],
                        verbose_name='Validade da Publicação',
                    ),
                ),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                (
                    'usuario_criador',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
